apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: morpheus
  description: Retrieve morpheus details
spec:
  type: openapi
  lifecycle: production
  owner: morpheus-relations-team
  system: morpheus-engagement-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: morpheus API
      license:
        name: MIT
    servers:
      - url: http://morpheus.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all morpheus
